// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAABS4EnG5eefb06XpT6iQ7KMPaDHrVJZo',
    appId: '1:119833315096:web:270b4b7481bc3c7bf0806d',
    messagingSenderId: '119833315096',
    projectId: 'gamaru-mobile-app',
    authDomain: 'gamaru-mobile-app.firebaseapp.com',
    storageBucket: 'gamaru-mobile-app.appspot.com',
    measurementId: 'G-GVWK3G0F1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5dKocY8FMDdp7YmHv6RtuDG7PjoANmM',
    appId: '1:119833315096:android:3b6f4fd488b2f98bf0806d',
    messagingSenderId: '119833315096',
    projectId: 'gamaru-mobile-app',
    storageBucket: 'gamaru-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjBbp6mnMT7YB0jpvvB6pAdXq5TEPWbc',
    appId: '1:119833315096:ios:1bd9a5bc74a9072df0806d',
    messagingSenderId: '119833315096',
    projectId: 'gamaru-mobile-app',
    storageBucket: 'gamaru-mobile-app.appspot.com',
    iosClientId: '119833315096-3pk8781mf9p0gnbj6qd34qdk11blqdmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamaruMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjBbp6mnMT7YB0jpvvB6pAdXq5TEPWbc',
    appId: '1:119833315096:ios:0b9d7f6e52ab705df0806d',
    messagingSenderId: '119833315096',
    projectId: 'gamaru-mobile-app',
    storageBucket: 'gamaru-mobile-app.appspot.com',
    iosClientId: '119833315096-jd5ph3lvg0afcd0so3q261p4fbldhff2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamaruMobileApp.RunnerTests',
  );
}
